### ISSUE TITLE
履歴ページのデザインを変更

### ISSUE THREAD

**Issue by Taito-Code** [ryoheinan/MorphoMusicClient#3]
![IMG_8553](https://user-images.githubusercontent.com/70618595/131256451-260cb2b2-a5a2-447c-b0dc-3c9b2fe24ad5.jpg)
BUYボタンの部分などがiTunesのようなイメージがあるので、Spotifyカラーにできたらしたい。

**Comment by ryoheinan** [comment]
Spotifyの[デザインガイドライン](https://developer.spotify.com/documentation/general/design-and-branding/#using-our-colors)によると、Spotifyの緑色は#1DB954らしいね

**Comment by ryoheinan** [comment]
Flex MessageのURLボタンも統一した方が良いのかな？

**Comment by Taito-Code** [comment]
> Spotifyの[デザインガイドライン](https://developer.spotify.com/documentation/general/design-and-branding/#using-our-colors)によると、Spotifyの緑色は#1DB954らしいね

**Comment by Taito-Code** [comment]
統一したほうが良さそうだね！

**Comment by Taito-Code** [comment]
一応Flex MessageのURLボタンは変更しました👍

**Comment by ryoheinan** [comment]
> 一応Flex MessageのURLボタンの色は変更しました👍
> [Taito-Code/MorphoMusicBackend@8997421](https://github.com/Taito-Code/MorphoMusicBackend/commit/89974218e0e1875ccbed328799ad700b7dec1795)

🙇‍♂️
